### ISSUE TITLE
hasTable() and hasKey() return false for inline tables

### ISSUE THREAD

**Issue by emillaine** [jdfergason/swift-toml#3]
This seems to be a bug (tested in v0.3.0). I think both of them should return true.

Here's a commit that adds a test case which catches these: https://github.com/jdfergason/swift-toml/commit/7cfa9469dc9d4ea78d2cac6a10f2d801579b2ff5. Feel free to merge.

I'm not sure how to fix this though.

**Comment by emillaine** [comment]
Also, it seems that the `table()` getter doesn't find inline tables.

**Comment by jdfergason** [comment]
I think I got this fixed:
- `hasKey` now reports true for tables and key/value pairs if they exist in the Toml document
- `hasTable` now correctly reports true for inline tables
- `table` now works
- updated testSimple to include test cases for hasTable and hasKey on the inline table

Available in e0f541f0848e7977c9dc531ddb81a5a791e163ec and created v0.3.1 release

**Comment by emillaine** [comment]
👍
